### ISSUE TITLE
Can get text from nested object ?

### ISSUE THREAD

**Issue by thuandoan274** [nicksnyder/go-i18n#121]
I wanna organize my file text to be more clarification like this
```
[Tip]
    NotEnoughCoin = "Not enough coin"

[Follow]
    HasAFollowing = "Has someone just following you"
```
Thank you!

**Comment by nicksnyder** [comment]
The file format does not support grouping in a hierarchical manner, and I don't think I want to add that because it would complicate parsing the file.

Instead, you can prefix message ids like this:
```
Tip.NotEnoughCoin = "Not enough coin"

Follow.HasAFollowing = "Has someone just following you"
```

or you can use comments like this

```
# Tip
NotEnoughCoin = "Not enough coin"

# Follow
HasAFollowing = "Has someone just following you"
```

**Comment by adhatama** [comment]
Hi @nicksnyder, I'm having an issue using your dot examples.

```
Tip.NotEnoughCoin = "Not enough coin"
```

`panic: Near line 1 (last key parsed ''): bare keys cannot contain '.'`

**Comment by adhatama** [comment]
@nicksnyder Thanks you. Using double quote works `"Tip.NotEnoughCoin = "Not enough coin"`
I used https://github.com/BurntSushi/toml for the toml library.

But I'm still having an issue if I want to use plurals.
```
This one without double quotes
[Tip.NotEnoughCoin]
one = "Not enough coin"
other = "Not enough coins"
```
```
This one with double quotes
["Tip.NotEnoughCoin"]
one = "Not enough coin"
other = "Not enough coins"
```

Then I call it
```
val, err := localizer.Localize(
    &i18n.LocalizeConfig{
        MessageID: "Tip.NotEnoughCoin",
        PluralCount: 2,
    },
)
```
The one without double quotes give this error
```
panic: expected value for key "NotEnoughCoin" be a string but got map[string]interface {}{"one":"Not enough coin", "other":"Notenough coins"}
```

And when I use double quotes, it says `message "Tip.NotEnoughCoin" not found`

Is it because this library or the toml library?

**Comment by nicksnyder** [comment]
I don’t don’t know. When pasting in a panic it is useful to include the whole trace.

You are the one with the reproducible example and the panic stack trace so please investigate :)

**Comment by benoitmasson** [comment]
I agree with @thuandoan274 and @maeglindeveloper (issue #135), this would be really useful and make translation files much more readable.

As JSON, TOML and YAML parsers already support nested data, the change in code wouldn't be that huge, you'd only have to add some recursion in the `internal.ParseMessageFileBytes()` function to scan the `data` map in depth.

I'll try to think about it too when I have some time.

**Comment by nicksnyder** [comment]
I am still confused on the motivation here and I am not convinced that the linked PR is necessarily the right solution.

It seems like the main motivation is the readability of the source files, not the actual nesting of the data. To me, this means that we should look for a solution that doesn't require actually nesting the data (and therefore wouldn't require a code change).

I already suggested one workaround: quoting the keys that contain dots. It seems like the plural case doesn't work though. Why? I don't have time to investigate this myself but I would want to know the answer to that question before merging other PRs.

It is also possible to use a `_` or `-` or even no separator instead of `.` to avoid this problem. Consider all of these possibilities:

Option 1:
```toml
LoginUsername = "Username"
LoginPassword = "Password"

RegistrationPhoneNumber = "Phone number"
RegistrationFirstName = "First name"
RegistrationConfirmation = "Account registration successful"
```

Option 2:
```toml
Login-Username = "Username"
Login-Password = "Password"

Registration-PhoneNumber = "Phone number"
Registration-FirstName = "First name"
Registration-Confirmation = "Account registration successful"
```

Option 3:
```toml
Login_Username = "Username"
Login_Password = "Password"

Registration_PhoneNumber = "Phone number"
Registration_FirstName = "First name"
Registration_Confirmation = "Account registration successful"
```

Option 4:
```toml
"Login.Username" = "Username"
"Login.Password" = "Password"

"Registration.PhoneNumber" = "Phone number"
"Registration.FirstName" = "First name"
"Registration.Confirmation" = "Account registration successful"
```

Option 5:
```toml
[Login]
  Username = "Username"
  Password = "Password"

[Registration]
  PhoneNumber = "Phone number"
  FirstName = "First name"
  Confirmation = "Account registration successful"
```

Option 6:
```toml
Login.Username = "Username"
Login.Password = "Password"

Registration.PhoneNumber = "Phone number"
Registration.FirstName = "First name"
Registration.Confirmation = "Account registration successful"
```

Options 1, 2, 3 work today without a code change.
Options 1, 2, 3, 4, 6 result in keys that can be found using code search and I would argue are more readable than option 5 for longer lists where the group context is lost.

I don't think options 4, 6 are better than 1, 2, 3, so I don't think it is worth adding implementation complexity to support those cases.

If you strongly prefer option 4, please investigate why plurals don't work and report back. I suspect the answer will be "toml doesn't support that" or "there is a bug in the toml library that needs to be fixed". I don't think it is worth implementation complexity in this library to work around the former, and the bug should be fixed directly in the toml library in the latter case.

If you strongly prefer option 5 over the others, please explain why. In my mind it is strictly worse due to being unable to search for the translation keys using code search and it requires adding complexity to the implementation.
