### ISSUE TITLE
segfault nil pointer dereference

### ISSUE THREAD

**Issue by dalu** [nicksnyder/go-i18n#205]
Following error
```
goroutine 20 [running]:
testing.tRunner.func1(0xc00019e100)
	/usr/lib/go/src/testing/testing.go:874 +0x3a3
panic(0xa49ae0, 0x1066bf0)
	/usr/lib/go/src/runtime/panic.go:679 +0x1b2
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).getTemplate(0xc0000f5d68, 0xaf9a71, 0x1c, 0x0, 0x1, 0xc0000f5cd8, 0x91e5d0, 0xacc0e0)
	/home/darko/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.2/i18n/localizer.go:176 +0x3d
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).LocalizeWithTag(0xc0000f5d68, 0xc0000f5da8, 0x2, 0xc0001c7590, 0x2, 0x2, 0xc0000f5db8, 0x40dc96, 0xc0001891a0)
	/home/darko/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.2/i18n/localizer.go:149 +0xe7
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).Localize(...)
	/home/darko/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.2/i18n/localizer.go:104
git.icod.de/dalu/socialthing/service.(*Service).LanguageTranslate(0xc000097fc0, 0xc0001c7500, 0xaedcd3, 0x2, 0xaf9a71, 0x1c, 0x0, 0x0, 0x0, 0x0)
	/home/darko/go/src/git.icod.de/dalu/socialthing/service/language.go:39 +0x179
git.icod.de/dalu/socialthing/service.(*Service).MailSendActivation(0xc000097fc0, 0xaf329b, 0x10, 0xaee86a, 0x6, 0x0, 0x0, 0x0, 0x230415220000000f, 0x5db3200d)
	/home/darko/go/src/git.icod.de/dalu/socialthing/service/mail.go:28 +0x29d
git.icod.de/dalu/socialthing/service.TestService_MailSendActivation(0xc00019e100)
	/home/darko/go/src/git.icod.de/dalu/socialthing/service/mail_test.go:12 +0xdc
testing.tRunner(0xc00019e100, 0xb15488)
	/usr/lib/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:960 +0x350

Process finished with exit code 1
```

It seems like the localizer expects a lc.DefaultMessage value.
It panics in line 176 of localizer.go
```go
	fastTag, template := l.matchTemplate(id, defaultMessage, l.bundle.matcher, l.bundle.tags)
```

my Service.LanguageTranslate() looks like this:
```go
func (s *Service) LanguageTranslate(ctx map[string]interface{}, lang string, fragment string) (string, error) {
	localizer := i18n.NewLocalizer(s.bundle, lang)
	lc := new(i18n.LocalizeConfig)
	lc.MessageID = fragment
	lc.TemplateData = ctx
	translated, e := localizer.Localize(lc)
	if e != nil {
		s.logger.Error(e)
		return translated, e
	}
	return translated, nil
}
```

It is initialized with
```go
func (s *Service) initLanguageService() error {
	bundle := i18n.NewBundle(language.English)
	bundle.RegisterUnmarshalFunc("toml", toml.Unmarshal)
	langs := []string{"en", "de"}
	for _, v := range langs {
		f, e := s.fs.Open(fmt.Sprintf("translation/%s.toml", v))
		if e != nil {
			return e
		}
		buf, e := ioutil.ReadAll(f)
		if e := f.Close(); e != nil {
			return e
		}
		msg, e := bundle.ParseMessageFileBytes(buf, fmt.Sprintf("translation/%s.toml", v))
		if e != nil {
			return e
		}
		fmt.Println(msg)
	}
	return nil
}
```

translation/en.toml
```toml
[MailAccountActivation]
description = "account activation email"
other = """\
Dear {{ .Email }},

your account was created. In order to use the full functionality you need to verify your email address.
Please click the following link to verify your account:

https://{{ .Domain }}/account/manage/verify_email?code={{ .Code }}

Best regards,
"""

[MailAccountActivationSubject]
description = "account activation email subject"
other = "{{ .Domain }} account activation"

[MailAccountReset]
description = "account reset email"
other = """
Dear {{ .Email }},

you have requested a password reset.
Please click the following link to reset your password:

https://{{ .Domain }}/account/manage/reset_password?email={{ .Email }}&code={{ .Code }}

Best regards,
"""

[MailAccountResetSubject]
description = "account reset email subject"
other = "{{ .Domain }} reset password"
```
translation/de.toml
```toml
[MailAccountActivation]
description = "account activation email"
other = """\
Hallo {{ .Email }},

das Konto wurde erstellt. Um den vollen Funktionsumfang zu nutzen muss deine Emailadresse verifiziert werden.
Bitte klicke den folgenden Link um dein Konto zu verifizieren:

https://{{ .Domain }}/account/manage/verify_email?code={{ .Code }}

Beste Grüße,"""

[MailAccountActivationSubject]
description = "account activation email subject"
other = "{{ .Domain }} Kontoverifizierung"

[MailAccountReset]
description = "account reset email"
other = """\
Hallo {{ .Email }},

jemand hat versucht dein Passwort zurückzusetzen.
Falls du das warst klick bitte den folgenden Link um dein Passwort zurückzusetzen:

https://{{ .Domain }}/account/manage/reset_password?email={{ .Email }}&code={{ .Code }}

Falls du das nicht warst, ignoriere diese Email.

Beste Grüße,"""

[MailAccountResetSubject]
description = "account reset email subject"
other = "{{ .Domain }} Passwort zurücksetzen"
```
