### ISSUE TITLE
Add TOML support

### ISSUE THREAD

**Issue by bep** [nicksnyder/go-i18n#61]
As discussed in this thread:

https://github.com/spf13/hugo/issues/2577

We use go-i18n in Hugo and it works great, but the number one related question we get on the support forum comes from people having a hard time getting their language files in YAML right (indentation issues, mostly).

So it would be nice if go-i18n could support the simpler TOML format and also optionally support a slightly flatter data format, so we could write:

```TOML
[[d_days]]
one = "{{.Count}} day"
other = "{{.Count}} days"

[[string_id_2]]
other = "Some other translation"
``` 

/cc @moorereason @bogem
