### ISSUE TITLE
Add flatter data file structure

### ISSUE THREAD

**Issue by moorereason** [nicksnyder/go-i18n#62]
A flatter data file structure would be beneficial.  Implementation should maintain support of existing format.

### JSON
```json
{
  "d_days": {
    "one": "{{.Count}} day",
    "other": "{{.Count}} days"
  },
  "string_id_2": {
    "other": "Some other translation"
  }
}
```

### YAML
```yaml
d_days:
  one: "{{.Count}} day"
  other: "{{.Count}} days"

string_id_2:
  other: Some other translation
```

### TOML (assuming #61)
```toml
[d_days]
one = "{{.Count}} day"
other = "{{.Count}} days"

[string_id_2]
other = "Some other translation"
```
