### ISSUE TITLE
Translating without count returns translation key

### ISSUE THREAD

**Issue by Niondir** [nicksnyder/go-i18n#77]
I have a translation like this
```
[customer]
  one = "Kunde"
  other = "Kunden"
```

And call

`{{T "customer"}}`

The restult is "customer" where I would expect one of the defined translations. I would suggest to use "other" for undefined amounts.

When using `{{T "customer" 2}}` everything works fine.

**Comment by Niondir** [comment]
As a fix 

```
func (pt *pluralTranslation) Template(pc language.Plural) *template {
	return pt.templates[pc]
}
```

Must handle `plural.Invalid` and return "other" instead.

**Comment by bogem** [comment]
> Must handle plural.Invalid and return "other" instead.

It works only for languages and words, where could be only "one" and "other" plural categories.
But it will not work for Russian language. The same word (customer) in Russian language looks like this:
```toml
[customer]
one = "клиенты" # 1, 21, 31, 41, ...
few = "клиента" # 2~4, 22~24, 32~34, 42~44, 52~54, 62, 102, ...
many = "клиентов" # 0, 5~19, 100, 1000, 10000, ...
other = "клиента" # 0.0~1.5, 10.0, 100.0, 1000.0, ...
```

So I don't think that the usage of "other" by default is a correct solution. IMHO developer should set a number explicitly (`{{T "customer" 2}}`) depending on the case.

**Comment by Niondir** [comment]
Actually my case was a Menu navigation item. You might be right, for my case I choose to use a different key to distinguish this kind of special case.

**Comment by bogem** [comment]
For your case I propose to create one more string with only one plural case ("other"):
```toml
[customer_menu_item]
other = "Kunden"
```

and use it as `{T "customer_menu_item"}`.
